alter session set "_ORACLE_SCRIPT"=true; 
--DROP USER

--DROP USER em CASCADE;
    
--CREATE USER
CREATE USER em IDENTIFIED BY 123;

--GRANT PRIVILEGES
GRANT CONNECT, RESOURCE, DBA TO em;
GRANT CREATE USER TO em;
GRANT ALTER USER TO em;
GRANT DROP USER TO em;
GRANT CREATE SESSION TO em;